import Footer from "@/components/Footer"
import Header from "@/components/Header"
import './styles.css'

export const metadata = {
  title: {
    default: "nextjs meta ",
    template: "%s | NextJs"
  },
  description: "generated by auto"
}

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
